baseURL = "/"
relativeURLs = true
uglyURLs = true
disablePathToLower = true
languageCode = "en-us"
title = "Swarm Bee Documentation"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

#[[menu.main]]
#    name = "Home"
#    url = "/"
#    weight = 1

#[[menu.main]]
#    name = "API reference"
#    url = "/bee-docs/API/index.html"
#    weight = 2

#[[menu.main]]
#    name = "API reference on Swarm"
#    url = "https://gateway.ethswarm.org/files/39b9e038943a0e1d45feb5712966a1f53699971a39d7bf1bffab5b7f2e055c6f"
#    weight = 3

[params]
  google_analytics_id=""
  homepage_button_link = '/bee-docs/introduction.html'
  homepage_button_text = 'Swarm Bee Docs'
  homepage_intro = 'Swarm Bee - Storage and communication infrastructure for a sovereign digital society.'
  homepage_image = '/swarm-logo.jpg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Swarm Bee - Storage and communication infrastructure for a sovereign digital society."
    meta_og_title = "Swarm Bee Documentation"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@ethswarm"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/swarm.png"
